import apiApp from "../../functions/api/app";
import type { Env } from "../../functions/lib/types";

// Derived structurally from apiApp.fetch's own declared signature rather
// than naming the ambient `ExecutionContext` type directly — this repo's
// worker-configuration.d.ts (generated by `wrangler types`) and
// @cloudflare/workers-types declare that name with slightly different
// member sets depending on their exact installed versions, and Hono's own
// c.executionCtx getter matches only one of them. Deriving from the
// function signature sidesteps having to pick a "winning" declaration.
export type ApiExecutionContext = NonNullable<Parameters<typeof apiApp.fetch>[2]>;

// Lets route loaders call the existing Hono API in-process — same isolate,
// no network hop — so loaders reuse 100% of the filter/sort/serialize logic
// already in functions/api/app.ts instead of duplicating D1 queries.
export async function apiFetch(path: string, env: Env, ctx: ApiExecutionContext): Promise<Response> {
  return apiApp.fetch(new Request(`https://internal.invalid${path}`), env, ctx);
}
